apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sample-app
  namespace: default
  labels:
    app:  sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  sample-app
    spec:
      containers:
      - name:  sample-app
        image:  quay.io/embik/sample-app:v0.1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
          name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: default
spec:
  selector:
    app:  sample-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
